### ISSUE TITLE
Stable 318710 Compilation Error

### ISSUE THREAD

**Issue by kesumin** [unknown81311/BetterMediaPlayer#21] opened 2024-08-15 17:15 UTC
stable 318710 (5b3a6a2) Host 1.0.9157 x64 (50412) Build Override: N/A Windows 11 64-bit (10.0.22631)
BetterDiscord Core v1.10.2

```
TypeError: Cannot read properties of undefined (reading 'useStateFromStores')
at eval (betterdiscord://plugins/BetterMediaPlayer.plugin.js:61:33)
at N.requireAddon (betterdiscord/renderer.js:5:28601)
at N.loadAddon (betterdiscord/renderer.js:5:6221)
at N.loadAddon (betterdiscord/renderer.js:5:26269)
at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
at N.initialize (betterdiscord/renderer.js:5:3093)
at N.initialize (betterdiscord/renderer.js:5:25382)
at Object.startup (betterdiscord/renderer.js:5:408589)
```

**Comment by maciupikciuxd** [comment] 2024-08-23 17:46
Same problem, not working since download

**Comment by doggybootsy** [comment] 2024-08-24 02:36
Duplicate of https://github.com/unknown81311/BetterMediaPlayer/issues/20

**Closed by doggybootsy** 2024-08-24 02:36 UTC
