### ISSUE TITLE
error loading

### ISSUE THREAD

**Issue by Darkn8tT** [unknown81311/BetterMediaPlayer#19] opened 2024-06-28 08:49 UTC
TypeError: Cannot read properties of undefined (reading 'useStateFromStores')
    at eval (betterdiscord://plugins/BetterMediaPlayer.plugin.js:61:33)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.reloadAddon (betterdiscord/renderer.js:5:7111)
    at betterdiscord/renderer.js:5:4235

**Comment by doggybootsy** [comment] 2024-06-28 15:25
duplicate of https://github.com/unknown81311/BetterMediaPlayer/issues/17 and https://github.com/unknown81311/BetterMediaPlayer/issues/18

**Closed by doggybootsy** 2024-06-28 15:25 UTC
