### ISSUE TITLE
[BUG] BetterMediaPlayer can´t be complied 

### ISSUE THREAD

**Issue by BlueStarBRS** [unknown81311/BetterMediaPlayer#8] opened 2022-10-26 17:48 UTC
Info about the console: 
![image](https://user-images.githubusercontent.com/25110093/198099368-679baa37-47e4-4598-9ca5-5649d07885ab.png)

**Comment by doggybootsy** [comment] 2022-10-26 18:48
Duplicate of https://github.com/unknown81311/BetterMediaPlayer/issues/7

**Closed** 2022-10-26 18:48 UTC
